# Site settings
title: kab
tagline: "One technophile's reference library"
url: "http://kab.bestul.us/" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
